### ISSUE TITLE
Failure management

### ISSUE THREAD

**Issue by jotak** [hawkular/hawkular-dropwizard-reporter#16]
We must have a fallback strategy when hawkular is not reachable.
The main use case is with the C* metrics reporter, on startup Hawkular may not be ready so that tags & metrics are lost.

On failure, metrics & tags must be kept in memory for a configurable amount and/or duration, to be sent again later.

**Comment by jsanda** [comment]
In OpenShift the start up order of the hawkular-metrics server and Cassandra is not fixed, meaning hawkular-metrics can start first and vice-versa. During its start up hawkular-metrics establishes a connection to the Cassandra connection. If creating the connection fails, we continue retrying with a back off delay since we know that Cassandra might not yet be started.

Since we know this can and will happen, it might good to log fully exceptions of failed requests at DEBUG and a more brief message at INFO.
